### ISSUE TITLE
Extension crash when double-clicking on some results

### ISSUE THREAD

**Issue by lgolding** [microsoft/sarif-visualstudio-extension#122]
1. Save the attached file as .sarif (without the .txt extension).

    [Bug122.sarif.txt](https://github.com/microsoft/sarif-visualstudio-extension/files/4446933/Bug122.sarif.txt)

2. Open the file in VS.

3. Double-click the second result.

    The file opens (assuming you have an ado enlistment at c:\ado).

4. Double-click the first result.

    VS displays a yellow error bar "An exception of type ArgumentOutOfRangeException has been encountered. This may be caused by an exception." The file does not open.

5. Click Open log file to see this exception:

```
System.ArgumentOutOfRangeException: The value cannot be negative.
Parameter name: offset
Actual value was -1.
   at Microsoft.CodeAnalysis.Sarif.NewLineIndex.GetOffsetInfoForOffset(Int32 offset)
   at Microsoft.CodeAnalysis.Sarif.FileRegionsCache.PopulatePropertiesFromCharOffsetAndLength(NewLineIndex newLineIndex, Region region)
   at Microsoft.CodeAnalysis.Sarif.FileRegionsCache.PopulateTextRegionProperties(NewLineIndex lineIndex, Region inputRegion, String fileText, Boolean populateSnippet)
   at Microsoft.Sarif.Viewer.SarifErrorListItem.RemapFilePath(String originalPath, String remappedPath) in C:\dev\sarif-visualstudio-extension\src\Sarif.Viewer.VisualStudio\Models\SarifErrorListItem.cs:line 470
   at Microsoft.Sarif.Viewer.CodeAnalysisResultManager.RemapFileNames(IList`1 sarifErrors, String originalPath, String remappedPath) in C:\dev\sarif-visualstudio-extension\src\Sarif.Viewer.VisualStudio\CodeAnalysisResultManager.cs:line 543
   at Microsoft.Sarif.Viewer.CodeAnalysisResultManager.TryRebaselineAllSarifErrors(Int32 runId, String uriBaseId, String originalFilename) in C:\dev\sarif-visualstudio-extension\src\Sarif.Viewer.VisualStudio\CodeAnalysisResultManager.cs:line 336
   at Microsoft.Sarif.Viewer.ResultTextMarker.NavigateTo(Boolean usePreviewPane) in C:\dev\sarif-visualstudio-extension\src\Sarif.Viewer.VisualStudio\ResultTextMarker.cs:line 71
   at Microsoft.Sarif.Viewer.ErrorList.SarifTableControlEventProcessorProvider.EventProcessor.PreprocessNavigate(ITableEntryHandle entryHandle, TableEntryNavigateEventArgs e) in C:\dev\sarif-visualstudio-extension\src\Sarif.Viewer.VisualStudio\ErrorList\SarifTableControlEventProcessorProvider.cs:line 96
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass40_0.&lt;OnEntryElementNavigate&gt;b__2(ITableControlEventProcessor p, ITableEntryHandle entry)
   at Microsoft.VisualStudio.Shell.TableControl.Implementation.TableControlEventManager.&lt;&gt;c__DisplayClass60_1`1.&lt;EventProcessorHandler&gt;b__0()
   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

Note: You only see the exception bar the first time you double-click the result. To see it again, close and reopen VS.

**Comment by lgolding** [comment]
Note to self: From examining the file, it looks like the problem is that the `artifactLocation` objects have `index` properties, but there is no `run.artifacts` array to index into.

**Comment by eddynaka** [comment]
@yongyan-gh , let's check this!

**Comment by yongyan-gh** [comment]
@eddynaka can you download the file in the issue? I cannot download it
can I enlist ado repo?

**Comment by yongyan-gh** [comment]
The issue can be repro directly by clicking on first result of the sample sarif log.
It is because the first result's physicalLocation.region.startline doesn't have value, its 0 by default.

```
          "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": ".config/CredScanSuppressions.json",
                  "uriBaseId": "TARGETROOT",
                  "index": 0
                },
                "region": {
                  "startColumn": 10,
                  "endColumn": 147,
                  "snippet": {
                    "text": "While an Olympics-related string appears in this file, and this team has historically used Olympics for passwords, this is not a password."
                  }
                }
              }
            }
```

In sarif-sdk [FileRegionCache.cs](https://github.com/microsoft/sarif-sdk/blob/8db262955431cc6fd8a8b085f8b0ccc8f2b4d34f/src/Sarif/FileRegionsCache.cs#L117), when startline is not greater than 0, code will calculate region start/end row/column using CharOffset and CharLength. And its CharOffset is not set, default value -1. 
```
            if (region.StartLine == 0)
            {
                // This means we have a region specified entirely via charOffset
                PopulatePropertiesFromCharOffsetAndLength(lineIndex, region);
            }
            else
            {
                PopulatePropertiesFromStartAndEndProperties(lineIndex, region, fileText);
            }
```
The second result has no issue since it has startline value set greater than 0. 
Looks like the code here expect the startline to be a positive number.

**Comment by eddynaka** [comment]
Looking at the sarif file and using the same in our validator, we can see a few issues:
- SARIF1009: artifact location does not exist
- SARIF1007: does not contain 'startLine', 'charOffset', or 'byteOffset' in the first result, causing the issue.
