### ISSUE TITLE
Sarif Viewer causes crash

### ISSUE THREAD

**Issue by ErikEJ** [microsoft/sarif-visualstudio-extension#623]
In Visual Studio 17.12.0.

I cannot uninstall, as the Sarif extension is required in VS:

```
---------------------------
Microsoft Visual Studio
---------------------------
System.String[] extension cannot be uninstalled from the system because it is required by the following installed extensions:Microsoft.VisualStudio.ExtensionManager.InstalledExtensionImpl
---------------------------
OK   
---------------------------

```

```
CreateInstance failed for package [SQL Designer Package]Source: 'mscorlib' Description: Exception has been thrown by the target of an invocation.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Runtime.InteropServices.COMException: EnsurePane must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at Microsoft.Sarif.Viewer.OutputWindowTracerListener.EnsurePane() in D:\a\1\s\src\Sarif.Viewer.VisualStudio.Core\OutputWindowTracerListener.cs:line 65
   at Microsoft.Sarif.Viewer.OutputWindowTracerListener.Write(String message)
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at Microsoft.Data.Relational.Design.Package.DesignerPackage..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)System.Runtime.InteropServices.COMException (0x8001010E): EnsurePane must be called on the UI thread.
   at Microsoft.VisualStudio.Shell.ThreadHelper.ThrowIfNotOnUIThread(String callerMemberName)
   at Microsoft.Sarif.Viewer.OutputWindowTracerListener.EnsurePane() in D:\a\1\s\src\Sarif.Viewer.VisualStudio.Core\OutputWindowTracerListener.cs:line 65
   at Microsoft.Sarif.Viewer.OutputWindowTracerListener.Write(String message)
   at System.Diagnostics.TraceInternal.WriteLine(String message)
   at Microsoft.Data.Relational.Design.Package.DesignerPackage..ctor()

```

**Comment by ErikEJ** [comment]
This is fixed in VS 17.12.4
